import type { FlaggedClause, CountryConfig, MilestoneDate } from '../types/legal';

/**
 * Helper utility to trigger browser download safely with URL revocation
 */
function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  try {
    document.body.appendChild(a);
    a.click();
  } finally {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
}

/**
 * 1-Click Google Docs Export Handler
 * Formats a clean, professional document for Google Docs or Microsoft Word
 */
export function exportToGoogleDocs(title: string, contentHtml: string): void {
  const fullDocumentHtml = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1e293b; line-height: 1.6; }
    h1 { color: #0284c7; border-bottom: 2px solid #0284c7; padding-bottom: 8px; }
    h2 { color: #0f172a; margin-top: 24px; border-bottom: 1px solid #cbd5e1; padding-bottom: 4px; }
    h3 { color: #334155; margin-top: 16px; }
    .badge { display: inline-block; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 11px; }
    .critical { background-color: #fee2e2; color: #991b1b; }
    .high { background-color: #fef3c7; color: #92400e; }
    .statute-box { background-color: #f0fdf4; border-left: 4px solid #16a34a; padding: 12px; margin: 12px 0; }
    .disclaimer { background-color: #f1f5f9; border: 1px solid #cbd5e1; padding: 12px; font-size: 11px; color: #64748b; margin-top: 30px; }
  </style>
</head>
<body>
  ${contentHtml}
  <div class="disclaimer">
    <strong>NEXUS AI LEGAL DISCLAIMER:</strong> This document was automatically exported from NEXUS AI Legal Assistant. It provides preliminary legal information for informational purposes and does not constitute formal legal advice.
  </div>
</body>
</html>`;

  const blob = new Blob([fullDocumentHtml], { type: 'application/msword;charset=utf-8' });
  triggerDownload(blob, `${title.replace(/\s+/g, '_')}_GoogleDoc_${Date.now()}.doc`);
}

/**
 * 1-Click Google Calendar Sync Handler
 * Generates direct Google Calendar Web Link & downloadable .ics iCal file
 */
export function syncToGoogleCalendar(milestone: MilestoneDate): { calendarUrl: string; icsDownload: () => void } {
  const startDate = milestone.date.replace(/-/g, '');
  const endDate = startDate;

  const eventTitle = encodeURIComponent(`[NEXUS Legal Milestone] ${milestone.title}`);
  const details = encodeURIComponent(
    `Milestone Type: ${milestone.type.toUpperCase()}\nClause Section: ${milestone.clauseSection}\nDescription: ${milestone.description}\nGenerated by NEXUS AI Legal Assistant.`
  );

  const calendarUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${eventTitle}&dates=${startDate}/${endDate}&details=${details}`;

  const icsDownload = () => {
    const icsContent = `BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//NEXUS AI//Legal Milestone Calendar Sync//EN
BEGIN:VEVENT
SUMMARY:[NEXUS Legal Milestone] ${milestone.title}
DESCRIPTION:${milestone.description} (Clause Section: ${milestone.clauseSection})
DTSTART;VALUE=DATE:${startDate}
DTEND;VALUE=DATE:${endDate}
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR`;

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    triggerDownload(blob, `NEXUS_Milestone_${milestone.id}.ics`);
  };

  return { calendarUrl, icsDownload };
}

/**
 * Download Executive Audit Report (JSON format)
 */
export function downloadExecutiveAuditReport(
  fileName: string,
  country: CountryConfig,
  clauses: FlaggedClause[],
  beforeScore: number,
  afterScore: number
): void {
  const payload = {
    nexusEngine: 'NEXUS AI v3.0 (Google Vertex AI + Document AI + Statutory RAG)',
    timestamp: new Date().toISOString(),
    contractTitle: fileName,
    activeJurisdiction: {
      code: country.code,
      name: country.name,
      primaryStatutes: country.primaryStatutes
    },
    prototypeRemediationScore: {
      beforeRemediation: beforeScore,
      afterRemediation: afterScore,
    },
    executiveSummary: {
      totalClausesAnalyzed: clauses.length,
      remediatedCount: clauses.filter((c) => c.isRemediated).length,
      criticalUnresolved: clauses.filter((c) => c.riskLevel === 'critical' && !c.isRemediated).length,
      highUnresolved: clauses.filter((c) => c.riskLevel === 'high' && !c.isRemediated).length,
    },
    evaluatedClauses: clauses,
    safetyDisclaimer: `NEXUS AI provides preliminary legal information and document navigation under ${country.name} law for informational purposes. It does not replace formal legal advice.`
  };

  const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
  triggerDownload(blob, `NEXUS_Audit_Report_${country.code}_${fileName.replace(/\s+/g, '_')}_${Date.now()}.json`);
}
